--Drop Table Statements
/**
Drop TABLE CREDITCARD;
Drop TABLE CUSTOMER;
Drop TABLE CUSTOMERUSERACCOUNT;
Drop TABLE CREDITCARD;
Drop TABLE CUSTOMER_CREDITCARD;
Drop TABLE DISCOUNT;
Drop TABLE EZPLUS;
Drop TABLE RETAILCUSTOMER;
Drop TABLE COMPANY;
Drop TABLE CORPORATECUSTOMER;
Drop TABLE RENTALAGENCY;
Drop TABLE RESERVATIONSTATUS;
Drop TABLE VEHICLERENTALCATEGORY;
Drop TABLE RESERVATION;
Drop TABLE VEHICLESTATUS;
Drop TABLE VEHICLE;
Drop TABLE MINIVAN;
Drop TABLE CAR;
Drop TABLE SUV;
Drop TABLE CARGOVAN;
Drop TABLE RENTALINSURANCEOPTION;
Drop TABLE FUELOPTION;
Drop TABLE RENTALSTATUS;
Drop TABLE RENTAL;
Drop TABLE EMPLOYEEUSERACCOUNT;
Drop TABLE EMPLOYEE;
Drop Table Country;
Drop Table USState;
**/

--Create Table Statements

CREATE TABLE CUSTOMERUSERACCOUNT
(
UserAccountID Raw(16) DEFAULT SYS_GUID() PRIMARY KEY,
UserName VARCHAR(64) UNIQUE NOT NULL,
Password VARCHAR2(100) NOT NULL,
Email VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE CUSTOMER
(
CustomerID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
FirstName Varchar2(50) NOT NULL,
LastName VARCHAR2(50) NOT NULL,
BirthDate DATE NOT NULL,
AddressLine1 VARCHAR2(50) NOT NULL,
AddressLine2 VARCHAR2(50) NOT NULL,
City VARCHAR2(30) NOT NULL,
StateCode Char(2) NOT NULL,
ZipCode VARCHAR2(10) NOT NULL,
Country VARCHAR2(50) NOT NULL,
Phone VARCHAR2(20) NOT NULL,
Email VARCHAR2(100) UNIQUE NOT NULL,
DriverLicenseNumber VARCHAR2(16) UNIQUE NOT NULL,
DriverLicenseExpDate DATE NOT NULL,
CustomerUserAccountID RAW(16) NULL,
CustomerType Char(1) NOT NULL,

CONSTRAINT CUSTOMER_CustomerUserAccountID_FK FOREIGN KEY (CustomerUserAccountID) 
REFERENCES CUSTOMERUSERACCOUNT(UserAccountID)
);

CREATE TABLE CREDITCARD
(
CardNumber VARCHAR2(16) PRIMARY KEY NOT NULL,
OwnerName VARCHAR2(100) NOT NULL,
MerchantName VARCHAR2(100) NOT NULL,
ExpDate DATE NOT NULL,
AddressLine1 VARCHAR2(50) NOT NULL,
AddressLine2 VARCHAR2(50) NOT NULL,
City VARCHAR2(30) NOT NULL,
StateCode VARCHAR2(20) NOT NULL,
ZipCode VARCHAR2(10) NOT NULL,
Country VARCHAR2(50) NOT NULL,
CreditLimit NUMBER(6) NOT NULL,
ActivationStatus NUMBER(1) NOT NULL
);

CREATE TABLE CUSTOMER_CREDITCARD
(
CardNumber VARCHAR2(16) NOT NULL,
CustomerID NUMBER(6) NOT NULL,

CONSTRAINT Customer_CREDITCARD_PK PRIMARY KEY (CardNumber,CustomerID),

CONSTRAINT CardNumber_FK FOREIGN KEY (CardNumber) 
REFERENCES CREDITCARD(CardNumber) ON DELETE CASCADE,

CONSTRAINT CustomerID_FK FOREIGN KEY (CustomerID) 
REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE
);

CREATE TABLE DISCOUNT
(
DiscountID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
DiscountCode VARCHAR2(8) UNIQUE NOT NULL,
DiscountDesc VARCHAR2(30) NOT NULL
);

CREATE TABLE EZPLUS
(
EZPlusID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
EZPlusRewardsCode VARCHAR2(8) UNIQUE NOT NULL,
EZPlusRewardsEarnedPoints NUMBER(6) NULL
);

CREATE TABLE RETAILCUSTOMER
(
CustomerID NUMBER(6) NOT NULL,
DiscountID NUMBER(8) NULL,
EZPlusID NUMBER(6) NULL,

CONSTRAINT RETAILCUSTOMER_CustomerID_FK FOREIGN KEY (CustomerID) 
REFERENCES CUSTOMER(CustomerID)ON DELETE CASCADE,

CONSTRAINT RETAILCUSTOMER_DiscountID_FK FOREIGN KEY (DiscountID)
REFERENCES DISCOUNT(DiscountID),

CONSTRAINT RETAILCUSTOMER_EZPlusID_FK FOREIGN KEY (EZPlusID)
REFERENCES EZPLUS(EZPlusID)
);

CREATE TABLE COMPANY
(
CompanyID NUMBER(6) PRIMARY KEY NOT NULL,
CompanyName VARCHAR2(80) NOT NULL,
AddressLine1 VARCHAR2(50) NOT NULL,
AddressLine2 VARCHAR2(50) NOT NULL,
City VARCHAR2(30) NOT NULL,
StateCode Char(2) NOT NULL,
ZipCode VARCHAR2(10) NOT NULL,
Country VARCHAR2(50) NOT NULL,
ContactName VARCHAR2(100) NOT NULL,
ContactPhone VARCHAR2(20) NOT NULL,
ContactEmail VARCHAR2(100) UNIQUE NOT NULL,
CompanyDailyRentalRate NUMBER(5,2) NOT NULL
);

CREATE TABLE CORPORATECUSTOMER
(
CustomerID NUMBER(6) NOT NULL,
CompanyID NUMBER(6) NOT NULL,

CONSTRAINT CORPORATECUSTOMER_CustomerID_FK FOREIGN KEY (CustomerID)
REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE,

CONSTRAINT CORPORATECUSTOMER_CompanyID_FK FOREIGN KEY (CompanyID)
REFERENCES COMPANY(CompanyID) ON DELETE CASCADE
);

CREATE TABLE RENTALAGENCY
(
RentalAGencyID NUMBER(6) PRIMARY KEY NOT NULL,
RentalAgencyName VARCHAR2(50) NOT NULL,
AddressLine1 VARCHAR2(50) NOT NULL,
AddressLine2 VARCHAR2(50) NOT NULL,
City VARCHAR2(30) NOT NULL,
StateCode CHAR(2) NOT NULL,
Country VARCHAR2(50) NOT NULL,
ZipCode VARCHAR2(10) NOT NULL,
Phone VARCHAR2(20) NOT NULL,
Email VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE RESERVATIONSTATUS
(
ReservationStatusID NUMBER(1) PRIMARY KEY,
ReservationStatusDesc VARCHAR2(20) NOT NULL
);

CREATE TABLE VEHICLERENTALCATEGORY
(
VehicleRentalCategoryID NUMBER(2) PRIMARY KEY NOT NULL,
CategoryName VARCHAR2(30) UNIQUE NOT NULL,
CategoryDailyRentalRate NUMBER(5,2) NOT NULL
);

CREATE TABLE RESERVATION
(
ReservationID NUMBER(6) PRIMARY KEY NOT NULL,
CustomerID NUMBER(6) NOT NULL,
RentalAgencyID NUMBER(6) NOT NULL,
VehicleRentalCategoryID NUMBER(2) NOT NULL,
ReservationDropOffAgency NUMBER(6) NOT NULL,
ReservationPickUpDate DATE NOT NULL,
ReservationPickUpTime NUMBER(4)NOT NULL,
ReservationDropOffDate DATE NOT NULL,
ReservationDropOffTime NUMBER(4)NOT NULL,
ReservationStatusID NUMBER(1) NOT NULL,

CONSTRAINT RESERVATION_CustomerID_FK FOREIGN KEY (CustomerID) 
REFERENCES CUSTOMER(CustomerID),

CONSTRAINT RESERVATION_RentalAgencyID_FK FOREIGN KEY (RentalAgencyID)
REFERENCES RENTALAGENCY(RentalAgencyID),

CONSTRAINT RESERVATION_VehicleRentalCategoryID_FK FOREIGN KEY (VehicleRentalCategoryID)
REFERENCES VEHICLERENTALCATEGORY(VehicleRentalCategoryID),

CONSTRAINT RESERVATION_ReservationDropOffAgency_FK FOREIGN KEY (ReservationDropOffAgency)
REFERENCES RENTALAGENCY(RentalAgencyID),

CONSTRAINT RESERVATION_ReservationStatusID_FK FOREIGN KEY (ReservationStatusID)
REFERENCES RESERVATIONSTATUS(ReservationStatusID)
);

CREATE TABLE VEHICLESTATUS
(
VehicleStatusID Number(1) PRIMARY KEY NOT NULL,
HasDisabilityOPtion NUMBER(1) NOT NULL
);

CREATE TABLE VEHICLE
(
VehicleID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
VINNUMBER VARCHAR2(17) UNIQUE NOT NULL,
Make VARCHAR2(40) NOT NULL,
Model VARCHAR2(40) NOT NULL,
Year Date NOT NULL,
Color VARCHAR2(25) NOT NULL,
LicensePlateNumber VARCHAR2(8) NOT NULL,
LicensePlateState Char(2) NOT NULL,
Mileage NUMBER(9) NOT NULL,
TransmissionType VARCHAR2(40) NOT NULL,
SeatCapacity NUMBER(1) NOT NULL,
VehicleRentalCategoryID NUMBER(2) NOT NULL,
VehicleStatusID NUMBER(1) NOT NULL,
VehicleOwningAgencyID NUMBER(6) NOT NULL,
VehicleCurrentLocationAgencyID NUMBER(6) NOT NULL,
VehicleType CHAR(1) NOT NULL,

CONSTRAINT VEHICLE_VehicleRentalCategoryID_FK FOREIGN KEY (VehicleRentalCategoryID)
REFERENCES VEHICLERENTALCATEGORY(VehicleRentalCategoryID),

CONSTRAINT VEHICLE_VehicleStatusID_FK FOREIGN KEY (VehicleStatusID)
REFERENCES VEHICLESTATUS(VehicleStatusID),

CONSTRAINT VEHICLE_VehicleOwningAgencyID_FK FOREIGN KEY (VehicleOwningAgencyID)
REFERENCES RENTALAGENCY(RentalAgencyID),

CONSTRAINT VEHICLE_VehicleCurrentLocationAgencyID_FK FOREIGN KEY (VehicleCurrentLocationAgencyID)
REFERENCES RENTALAGENCY(RentalAgencyID)
);

CREATE TABLE MINIVAN
(
VehicleID Number(6) NOT NULL,
HasDisabilityOption NUMBER(1) NOT NULL,

CONSTRAINT MINIVAN_VehicleID_FK FOREIGN KEY (VehicleID)
REFERENCES VEHICLE(VehicleID)
);

CREATE TABLE CAR
(
VehicleID Number(6) NOT NULL,
TrunkCapacity NUMBER(4,2) NOT NULL,

CONSTRAINT CAR_VehicleID_FK FOREIGN KEY (VehicleID)
REFERENCES VEHICLE(VehicleID)
);

CREATE TABLE SUV
(
VehicleID Number(6) NOT NULL,
TowingCapacity NUMBER(4) NOT NULL,
IsAWD NUMBER(1) NOT NULL,

CONSTRAINT SUV_VehicleID_FK FOREIGN KEY (VehicleID)
REFERENCES VEHICLE(VehicleID)
);

CREATE TABLE CARGOVAN
(
VehicleID Number(6) NOT NULL,
CargoCapacity NUMBER(5,2) NOT NULL,
MaximumPayload NUMBER(4) NOT NULL,

CONSTRAINT CARGOVAN_VehicleID_FK FOREIGN KEY (VehicleID)
REFERENCES VEHICLE(VehicleID)
);

CREATE TABLE RENTALINSURANCEOPTION
(
RentalInsuranceOptionID NUMBER(1) PRIMARY KEY NOT NULL,
RentalInsuranceOptionDesc VARCHAR2(200) NOT NULL,
RentalInsuranceOptionAdditionalCost NUMBER(4,2) NOT NULL
);

CREATE TABLE FUELOPTION
(
FuelOptionID NUMBER(1) PRIMARY KEY NOT NULL,
FuelOptionDescVARCHAR2(50) NOT NULL
);

CREATE TABLE RENTALSTATUS
(
RentalStatusID NUMBER(1) PRIMARY KEY NOT NULL,
RentalStatusDesc VARCHAR2(50) NOT NULL
);

CREATE TABLE RENTAL
(
RentalAgreementID NUMBER(6) PRIMARY KEY NOT NULL,
CustomerID NUMBER(6) NOT NULL,
VehicleID NUMBER(6) NOT NULL,
RentalAgencyID NUMBER(6) NOT NULL,
RentalDropOffAgencyID NUMBER(6) NOT NULL,
ReservationID NUMBER(6) NULL,
RentalPickupDate DATE NOT NULL,
RentalPickUpTime NUMBER(4) NOT NULL,
RentalDropOffDate DATE NOT NULL,
RentalDropOffTime NUMBER(4) NOT NULL,
RentalPickUpOdometerValue NUMBER(6,1) NOT NULL,
RentalDropOffOdometerValue NUMBER(6,1) NOT NULL,
RentalFuelOptionID NUMBER(1) NOT NULL,
RentalInsuranceOptionID NUMBER(1) NOT NULL,
RentalStatusID NUMBER(1) NOT NULL,

CONSTRAINT RENTAL_CustomerID_FK FOREIGN KEY (CustomerID)
REFERENCES CUSTOMER(CustomerID),

CONSTRAINT RENTAL_VehicleID_FK FOREIGN KEY (VehicleID)
REFERENCES VEHICLE(VehicleID),

CONSTRAINT RENTAL_RentalAgencyID_FK FOREIGN KEY (RentalAgencyID)
REFERENCES RENTALAGENCY(RentalAgencyID),

CONSTRAINT RENTAL_RentalDropOffAgencyID_FK FOREIGN KEY (RentalDropOffAgencyID)
REFERENCES RENTALAGENCY(RentalAgencyID),

CONSTRAINT RENTAL_ReservationID_FK FOREIGN KEY (ReservationID)
REFERENCES RESERVATION(ReservationID),

CONSTRAINT RENTAL_RentalFuelOptionID_FK FOREIGN KEY (RentalFuelOptionID)
REFERENCES FUELOPTION(FuelOptionID),

CONSTRAINT RENTAL_RentalInsuranceOptionID_FK FOREIGN KEY (RentalInsuranceOptionID)
REFERENCES RENTALINSURANCEOPTION(RentalInsuranceOptionID),

CONSTRAINT RENTAL_RentalStatusID_FK FOREIGN KEY (RentalStatusID)
REFERENCES RENTALSTATUS(RentalStatusID)
);

CREATE TABLE EMPLOYEEUSERACCOUNT
(
UserAccountID Char(32) PRIMARY KEY NOT NULL,
UserName VARCHAR2(64) UNIQUE NOT NULL,
Password VARCHAR2(100) NOT NULL,
Email VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE EMPLOYEE
(
EmployeeID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
EmployeeFullName VARCHAR2(50) NOT NULL,
EmployeeLastName VARCHAR2(50) NOT NULL,
SSNumber VARCHAR(20)UNIQUE NOT NULL,
AddressLine1 VARCHAR2(50) NOT NULL,
AddressLine2 VARCHAR2(50) NOT NULL,
City VARCHAR(30) NOT NULL,
StateCode CHAR(2) NOT NULL,
ZipCode VARCHAR2(10) NOT NULL,
Country VARCHAR2(50) NOT NULL,
EmployeePhone VARCHAR2(20) NOT NULL,
EmployeeJobTitle VARCHAR2(25) NOT NULL,
EmployeeEmail VARCHAR2(100) UNIQUE NOT NULL,
EmployeeUserAccountID CHAR(32) NOT NULL,

CONSTRAINT EMPLOYEE_EmployeeUserAccountID_FK FOREIGN KEY (EmployeeUserAccountID)
REFERENCES EMPLOYEEUSERACCOUNT(UserAccountID)
);

CREATE TABLE COUNTRY
(
CountryID NUMBER(3) PRIMARY KEY NOT NULL,
CountryCode CHAR(2) UNIQUE NOT NULL,
CountryName VARCHAR2(50) NOT NULL
);

CREATE TABLE USSTATE
(
StateID NUMBER(1) PRIMARY KEY NOT NULL,
StateCode CHAR(2) UNIQUE NOT NULL,
StateName VARCHAR2(20) NOT NULL
);


